import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import SearchBar from "@/components/SearchBar";
import TagsBar from "@/components/TagsBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Damn Simple Notes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body> */}

      <body>
        <div className="main-bg">
          <img src="/images/ItalyClock.jpg" />
        </div>

        <div className="blursed">blurrrr</div>

        <div className="main-container">
          <Header />

          <SearchBar />

          <TagsBar />

          <div className="container mx-auto flex flex-col md:flex-row my-10">
            <aside className="w-full lg:w-1/3 xl:w-1/4 bg-gray-800 text-white p-4">
              Sidebar Content
            </aside>
            <main className="w-full lg:w-2/3 xl:w-3/4  p-4">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
